name: cloudwalk_test_mobile_engineer_2
description:

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # HttpClientAdapter
  http: ^1.1.0
  # Error Handling
  multiple_result: ^5.1.0
  # Cache Storage
  # path_provider: ^2.1.0
  cached_network_image: ^3.2.3
  # Local Storage
  localstorage: ^4.0.1+4
  # Modularity
  flutter_modular: ^6.0.4+1
  alice: ^0.3.3
  # State Management
  provider: ^6.0.5
  dio: ^5.3.2
  
dev_dependencies:
  # Tests
  flutter_test:
    sdk: flutter
  mocktail: 0.1.4
  faker: 2.0.0
  network_image_mock: 2.0.1
  # Linters
  flutter_lints: ^2.0.0
  lints: ^2.0.0

flutter:
  uses-material-design: true

fonts:
  - family: Secular_One
    fonts:
      - asset: assets/fonts/Secular_One/SecularOne-Regular.ttf
   

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
