name: nasa_apod_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_modular: ^6.0.4+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  remo_core:
    path: ../packages/remo_core

dev_dependencies:
  build_runner: ^2.4.8
  faker: 2.0.0 #2.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^2.0.0
  mocktail: 0.1.4 #1.0.2
  network_image_mock: 2.0.1

flutter:
  uses-material-design: true

fonts:
  - family: Secular_One
    fonts:
      - asset: assets/fonts/Secular_One/SecularOne-Regular.ttf

build_runner:
  scripts:
    buildDel: dart run build_runner build --delete-conflicting-outputs
    watchDel: dart run build_runner watch --delete-conflicting-outputs
    watch: dart run build_runner watch