name: nasa_apod_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  fluttely_core:
    path: ../fluttely_core
  flutter:
    sdk: flutter

dev_dependencies: # TODO: put dev_dependencies in fluttely_core?
  build_runner: ^2.4.5
  faker: 2.0.0 #2.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  mocktail: 0.1.4 #1.0.2
  network_image_mock: 2.0.1

flutter:
  uses-material-design: true

fonts:
  - family: Secular_One
    fonts:
      - asset: assets/fonts/Secular_One/SecularOne-Regular.ttf
