name: nasa_apod_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_strategy: ^0.2.0
  responsive_builder: ^0.7.0
  flutter_animate: ^4.1.1+1
 # HttpClientAdapter
  http: ^1.1.0
  # Error Handling
  multiple_result: ^5.1.0
  # Cache Storage
  # path_provider: ^2.1.0
  cached_network_image: ^3.2.3
  # Local Storage
  localstorage: ^4.0.1+4
  # Modularity
  flutter_modular: ^6.0.4+1
  alice: ^0.3.3
  # State Management
  provider: ^6.0.5
  # dartz: ^0.10.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  mocktail: 0.1.4
  faker: 2.0.0
  network_image_mock: 2.0.1
  # Linters
  lints: ^2.0.0

flutter:
  uses-material-design: true

fonts:
  - family: Secular_One
    fonts:
      - asset: assets/fonts/Secular_One/SecularOne-Regular.ttf