name: nasa_apod_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_strategy: ^0.2.0
  flutter_animate: ^4.1.1+1
  http: ^1.1.0
  # path_provider: ^2.1.0
  cached_network_image: ^3.3.0
  localstorage: ^4.0.1+4
  flutter_bloc: ^8.1.3
  flutter_modular: ^6.0.4+1
  alice: ^0.3.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  responsive_builder: ^0.7.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  mocktail: 0.1.4
  faker: 2.0.0
  network_image_mock: 2.0.1
  lints: ^2.0.0

flutter:
  uses-material-design: true

fonts:
  - family: Secular_One
    fonts:
      - asset: assets/fonts/Secular_One/SecularOne-Regular.ttf